# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c5a1250cc519b13d8f8535ec86c0c406ca1eef7b8bda9c0e5737425a1e7c947a6f36faaa598a45bb79c88b5db6803ac32e25b5e199278c606bedc48da94de9c

test:
  secret_key_base: e7226346743eb8210e001e9dc9500f2f21b66ae680613ce462149a07dfbd562b25677ad922695f3a255565825f22a7b47a1be65bceea0c9715e6a94a42548235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
